---
title: "Prioritizing management goals for stream biological integrity within the context of landscape constraints"
output: 
  word_document:
    reference_docx: my_styles.docx
bibliography: refs.bib
author: 'Marcus W. Beck (marcusb@sccwrp.org), Raphael D. Mazor (raphaelm@sccwrp.org), Scott Johnson (scott@aquaticbioassay.com), Karin Wisenbaker (karin@aquaticbioassay.com), Phil Markle (pmarkle@lacsd.org), Joshua Westfall (jwestfall@lacsd.org), Peter D. Ode (peter.ode@wildlife.ca.gov), Ryan Hill (hill.ryan@epa.gov), Chad Loflen (Chad.Loflen@waterboards.ca.gov), Martha Sutula (marthas@sccwrp.org), Eric D. Stein (erics@sccwrp.org)'
urlcolor: blue
link-citations: true
---

# Introduction

*	In many urban and agricultural areas the majority of stream miles are not healthy and in need of some level of management (cite SWAMP, SMC, NRSA)

* Unfortunately, there are not sufficient resources to restore all streams to reference conditions, nor is it practical

* Need a way to comprehensively evaluate streams across large spatial scales for “management potential”.  This allows establishment of reasonable expectations and prioritization of limited resources most effectively

* Once these large spatial scales are understood, sites can be prioritized by local managers to ensure resources are wisely allocated. 
     
* Goal: demonstrate application of a landscape model to classify and prioritize stream monitoring sites using estimated constraints on biological integrity. 
     * Build on knowledge and relationships developed through existing monitoring programs and apply that in a predictive manner across entire landscapes to inform decisions
     * Statewide application of the model
     * A case study is used to demonstrate how the model can be used to classify and prioritize by watershed using guidance from a regional stakeholder group. Specific questions that were addressed through the case study.
     
# Methods

### Study area and data sources

* Brief description of CA, stream types and designated uses, PSA regions, management interests (e.g., southern vs. northern CA)

* Data sources
     * Streamcat database used to quantify watershed land use at all sites
     * Streamcat data linked to NHD, reach as individual unit for model output
     * CSCI as measure of biological condition

### Building and validating landscape models

* Development of landscape model using statewide data

* Ag/Urban land in catchment as predictor of constraint
     * Chosen through vetted stakeholder process at the state level
     * Model incomplete by design, goal of explaining portion of biological response from large-scale constraints
     
* Quantile regression forests and range of model output

* Split between calibration/validation data, evaluation of performance  

### San Gabriel River watershed case study

* Overview of SGR watershed, land use, upper/lower watershed, etc.

* SGR management groups and SGRRMP

* General process of involving stakeholders in developing model, identifying priorities
     * Use of interactive application to facilitate

*Figure* SGR watershed 

### Reach classification, site performance, and prioritization

* Details about classification framework for stream reaches
     * Range of CSCI expectations at a reach relative to a chosen CSCI threshold (i.e., as a basis for defining reach classification)
     * Likely constrained, possibly constrained, possibly unconstrained, likely unconstrained

* Details about identifying site performance
     * Sites with observed scores above the upper limit of the reach expectation as "over-performing" and sites below the lower limit as "under-performing", within range as "expected"
     * Identified for each of four reach classifications
     * Further identified based on location to CSCI threshold to define "types" to prioritize

* Stakeholder process to assign management priorities by site types - observed scores in relation to stream class, performance, and CSCI threshol defines how a site is prioritized, also based on management interest (monitoring, permitting, etc.)

*Figure* flowchart for classification and performance identification

*Table* reach classification, site performance types and categories

*Figure* Site types template figure for prioritization

*Figure* Screenshot of web application

### Sensitivity analyses

* Reach classifications and site performance depend on the range of score expectations and the CSCI threshold

* Sensitivity analysis to evaluate effect of certainty in the model and CSCI threshold (strict, lax) on stream miles by priority category

### Unclassified reaches

* Some reaches were unclassifed if data were insufficient or if a catchment could not be defined

* Latter was more common, particularly in engineered channels or agricultural ditches

* A preliminary approach for assigning biological expectations to unclassified reaches is demonstrated for "typically" urban and agricultural reaches

# Results

### State-wide patterns

* Where does the model perform well, how does performance vary with validation and calibration datasets.

* What is the consistency of patterns? For example, percent stream miles as xyz by PSA.

*Figure* Statewide map. 

### Case study

* Extent, classification, prioritization

* Relationships with environmental variables for constrained/unconstrained locations. Maybe apply to hardened/non-hardened reaches in constrained locations. 

*Figure* Summary of extent of reach classification, site performance, selected examples

*Tables* Priority table(s) from stakeholder group

### Sensitivity analysis

* Statewide results - reach classification, site performance

* SGR application - where do priorities change related to which variables the model is most sensitive to? Do overall patterns remain?

*Table* Sensitivity results

### Unclassified reaches

* Extent of typical ag, typical urban statewide

* Framework for assigning unclassified reach to a class

* Statewide patterns, SGR patterns

*Table* Summary by location

# Discussion

* What is the value of identifying constrained channels?
     * Identification of constrained channels allows us to determine how best to spend limited resources and to focus on reaches where we have a decent chance of improving the biological condition.
     * Use of more data to develop context of assessment
     * Targeted management for desired outcomes
     * Informing decisions about future monitoring (i.e., prioritize future monitoring locations)

* What is useful about our approach compared to alternatives?
     * Field-based methods to identify constrained channels vs. landscape modelling
     * Related directly to biological condition and regulatory standards
     * Results are widely corraborated by other landscape studies - land use is big determinant of macroinvert assemblage

* What contributed to our success in defining priorities? 
     * Stakeholder involvement guided process, contributed to achieving goals
     * An interactive/iterative approach was used - we provided tools to facilitate (web apps) and we did not assume priorities

* Caveats of our aproach
     * What do priorities really mean? Depends on your interests, needs, values, etc.
     * Constrained may not always mean constrained - CSCI vs other biological indicators
     * Site-specific approaches are warranted in certain cases
     * Changing certainty or CSCI treshold - mechanistic effects and implications. Don't cook the books. 

* Future work
     * Ability to link with other assessment tools besides CSCI
     * Link with engineered channels study
     * Priorities statewide
     * Application to larger regions possible (national-scale), or how it can be applied in other areas
     
# Supplement

Online application.

